export type WithdrawRowType = {
	id: string;
	username: string;
	amount: string;
	method: 'IMPS' | 'UPI';
	status: string;
	age: string;
	kyc: string;
	flags: string;
	phoneNo: string;
	ip: string;
	os: string;
	device: string;
	agentName: string;
	accName: string;
	accNumber: string;
	ifsc: string;
	upiId: string;
	qr: string;
	riskPercentage: string;
	lastDeposit: string;
	totalDeposit: string;
	totalWithdraw: string;
	ggr: string;
	betsCountSinceLastDeposit: string;
	betsValueSinceLastDeposit: string;
	coverImageUrl: string;
	screenshotUrl: string;
};
